cache:
  paths:
  - node_modules/
  - .cache/

build:
  script:
  - yarn --ignore-engines install
  - ./node_modules/.bin/gatsby build --prefix-paths
  - cp -r ./public/* /var/www/html
  artifacts:
    name: website
    paths:
    - public
  only:
  - master
