cache:
  paths:
  - node_modules/

build:
  script:
  - yarn install
  - ./node_modules/.bin/gatsby build --prefix-paths
  - cp -r ./public/* /var/www/html/new
  artifacts:
    name: website
    paths:
    - public
  only:
  - master
