cache:
  paths:
  - node_modules/
  - .cache/

build:
  script:
  - yarn --ignore-engines install
  - ./node_modules/.bin/gatsby build --prefix-paths
  - rm -rf /var/www/html/*
  - cp -r ./public/* /var/www/html
  only:
  - master
